name: CI

on:
  # push:
  #   branches: [ main ]
  push:
    tags:
      - 'v*'

env:
  POLONG_CORE_TAG: v1.0.0
  POLONG_WEB_VERSION: 1.0.0

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: electronuserland/builder:wine-mono
      options: --user root
    steps:
      - uses: actions/checkout@v2
      
      - name: Package
        run: |
          chown -R root /github/home
          echo "下载核心"
          wget https://github.com/alx696/polong-core/releases/download/${POLONG_CORE_TAG}/polong-core-linux
          wget https://github.com/alx696/polong-core/releases/download/${POLONG_CORE_TAG}/polong-core-windows
          chmod +x polong-core-linux polong-core-windows
          echo "下载网页"
          wget https://github.com/alx696/polong-web/archive/refs/tags/v${POLONG_WEB_VERSION}.tar.gz
          tar zxf v${POLONG_WEB_VERSION}.tar.gz
          rm v${POLONG_WEB_VERSION}.tar.gz
          mv polong-web-${POLONG_WEB_VERSION} web
          echo "编译程序"
          npm install -g yarn
          yarn add electron --dev
          yarn add electron-builder --dev
          yarn --verbose
          yarn win
          yarn linux

      - name: Test
        run: ls dist

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          apt-get update
          apt-get install -y jq
          GIT_TAG=`echo $GITHUB_REF | sed 's/refs\/tags\///'`
          # get upload url
          API_UPLOAD_URL=`curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/releases \
          -d '{"tag_name":"'${GIT_TAG}'"}' \
          | jq --raw-output '.upload_url' \
          | sed 's/{?name,label}/?name/'`
          # upload
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @'dist/polong.deb' \
          ${API_UPLOAD_URL}=polong.deb
          # upload
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @'dist/polong.rpm' \
          ${API_UPLOAD_URL}=polong.rpm
          # upload
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @'dist/polong.exe' \
          ${API_UPLOAD_URL}=polong.exe
