name: CI

on:
  # push:
  #   branches: [ main ]
  push:
    tags:
      - 'v*'

env:
  POLONG_CORE_TAG: v1.0.0
  POLONG_WEB_VERSION: 1.0.0

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: electronuserland/builder:wine-mono
      options: --user root
    steps:
      - uses: actions/checkout@v2
      
      - name: Package
        run: |
          chown -R root /github/home
          echo "下载核心"
          wget https://github.com/alx696/polong-core/releases/download/${POLONG_CORE_TAG}/polong-core-linux
          wget https://github.com/alx696/polong-core/releases/download/${POLONG_CORE_TAG}/polong-core-windows
          chmod +x polong-core-linux polong-core-windows
          echo "下载网页"
          wget https://github.com/alx696/polong-web/archive/refs/tags/v${POLONG_WEB_VERSION}.tar.gz
          tar zxf v${POLONG_WEB_VERSION}.tar.gz
          rm v${POLONG_WEB_VERSION}.tar.gz
          mv polong-web-${POLONG_WEB_VERSION} web
          echo "编译程序"
          npm install -g yarn
          yarn add electron --dev
          yarn add electron-builder --dev
          yarn --verbose
          yarn win
          yarn linux

      - name: Test
        run: ls dist

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          # 多个文件时不要引号！
          files: |
            dist/polong.deb
            dist/polong.rpm
            dist/polong.exe
