name: Publish

on:
  push
  # push:
  #   tags:
  #     - 'v*'

env:
  POLONG_CORE_TAG: v1.0.0
  POLONG_WEB_VERSION: 1.0.0

jobs:

  windows:
    runs-on: ubuntu-latest
    container:
      image: electronuserland/builder:wine-mono
    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: |
          echo "当前用户:$USER"
          chown -R $USER /github/home
          echo "下载核心"
          wget https://github.com/alx696/polong-core/releases/download/${POLONG_CORE_TAG}/polong-core-linux
          wget https://github.com/alx696/polong-core/releases/download/${POLONG_CORE_TAG}/polong-core-windows
          echo "下载网页"
          wget https://github.com/alx696/polong-web/archive/refs/tags/v${POLONG_WEB_VERSION}.tar.gz
          tar zxf v${POLONG_WEB_VERSION}.tar.gz
          rm v${POLONG_WEB_VERSION}.tar.gz
          mv polong-web-${POLONG_WEB_VERSION} web
          npm install -g yarn
          yarn add electron --dev
          yarn add electron-builder --dev
          yarn --verbose && yarn win

#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - uses: actions/setup-node@v2
#       with:
#         node-version: 14

#     - name: Build
#       run: |
#         sudo apt install -y wget rpm
#         echo "下载核心"
#         wget https://github.com/alx696/polong-core/releases/download/${POLONG_CORE_TAG}/polong-core-linux
#         wget https://github.com/alx696/polong-core/releases/download/${POLONG_CORE_TAG}/polong-core-windows
#         echo "下载网页"
#         wget https://github.com/alx696/polong-web/archive/refs/tags/v${POLONG_WEB_VERSION}.tar.gz
#         tar zxf v${POLONG_WEB_VERSION}.tar.gz
#         rm v${POLONG_WEB_VERSION}.tar.gz
#         mv polong-web-${POLONG_WEB_VERSION} web
#         echo "打包Linux"
#         npm install -g yarn
#         yarn add electron --dev
#         yarn add electron-builder --dev
        
#     - uses: docker-practice/actions-setup-docker@master
#     - name: Build Windows
#       run: >
#         docker run -it --rm
#         --env ELECTRON_CACHE="/root/.cache/electron"
#         --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder"
#         --env DEBUG="electron-builder,electron-builder:*"
#         -v ${PWD}:/project
#         -v ${PWD##*/}-node-modules:/project/node_modules
#         -v ~/.cache/electron:/root/.cache/electron
#         -v ~/.cache/electron-builder:/root/.cache/electron-builder
#         -v ~/.cache/yarn:/usr/local/share/.cache/yarn
#         electronuserland/builder:wine-mono /bin/bash -c "yarn --verbose && yarn win"

  # build:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2

  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: 14

  #   - name: Build
  #     shell: powershell
  #     run: |
  #       echo "下载核心"
  #       (new-object System.Net.WebClient).DownloadFile("https://github.com/alx696/polong-core/releases/download/$POLONG_CORE_TAG/polong-core-linux", "polong-core-linux")
  #       wget -Uri "https://github.com/alx696/polong-core/releases/download/$POLONG_CORE_TAG/polong-core-windows"
  #       echo "下载网页"
  #       wget -Uri "https://github.com/alx696/polong-web/archive/refs/tags/v$POLONG_WEB_VERSION.tar.gz"
  #       tar zxf v$POLONG_WEB_VERSION.tar.gz
  #       rm v$POLONG_WEB_VERSION.tar.gz
  #       Rename-Item -Path polong-web-$POLONG_WEB_VERSION -NewName web
  #       echo "Package Windows"
  #       npm install -g yarn
  #       yarn add electron --dev
  #       yarn add electron-builder --dev
  #       yarn --verbose
  #       yarn win
  #       Get-ChildItem -Path dist



###

    # - name: Create release and upload assets
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
    #   with:
    #     files: |
    #       'dist/*.deb'
    #       'dist/*.rpm'
